export { default as AccountRecoverysection } from './AccountRecoverysection/+page.svelte'
export { default as Bannersection } from './Bannersection/+page.svelte'
export { default as Blogsection } from './Blogsection/+page.svelte'
export { default as ContactFormsection } from './ContactFormsection/+page.svelte'
export { default as Contentsection } from './Contentsection/+page.svelte'
export { default as CookieConsentsection } from './CookieConsentsection/+page.svelte'
export { default as Ctasection } from './Ctasection/+page.svelte';
export { default as CustomerLogosection } from './CustomerLogosection/+page.svelte';
export { default as Faqsection } from './Faqsection/+page.svelte';
export { default as Featuresection } from './Featuresection/+page.svelte';
export { default as Footersection } from './Footersection/+page.svelte'
export { default as Headersection } from './Headersection/+page.svelte';
export { default as Herosection } from './Herosection/+page.svelte';
export { default as LoginFormsection } from './LoginFormsection/+page.svelte';
export { default as Maintenancesection } from './Maintenancesection/+page.svelte'
export { default as Newslettersection } from './Newslettersection/+page.svelte';
export { default as Page404section } from './Page404section/+page.svelte';
export { default as Page500section } from './Page500section/+page.svelte'
export { default as Popupsection } from './Popupsection/+page.svelte';
export { default as Pricingsection } from './Pricingsection/+page.svelte';
export { default as RegisterFormsection } from './RegisterFormsection/+page.svelte';
export { default as ResetPasswordFormsection } from './ResetPasswordFormsection/+page.svelte';
export { default as SocialProofsection } from './SocialProofsection/+page.svelte';
export { default as Teamsection } from './Teamsection/+page.svelte';
export { default as Testimonialsection } from './Testimonialsection/+page.svelte'
export { default as UserOnboarding } from './UserOnboarding/+page.svelte';